version: "3.9"
services: 
  docker: 
    build: 
      context: ./kr-project/
      dockerfile: Dockerfile 
    container_name: django_app 
    env_file: 
      - ./kr-project/.env 
    restart: always 

  nginx: 
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx 
    restart: always 

  front: 
    build: 
      context: ./client/
      dockerfile: Dockerfile
    container_name: client_app 
    restart: always
  
 