version: "3"
services: 
  app: 
    build: 
      context: .
      dockerfile: ./kr-project/Dockerfile  
    container_name: django_app 
    environment:       
      - .env 
    entrypoint: ['uwsgi', 'uwsgi.ini']
    restart: always 
    volumes:
      - static_files:${STATIC_ROOT}

  nginx: 
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx 
    restart: always 
    volumes:
      - static_files:${STATIC_PATH_NGINX} 
    depends_on:
      - app

  front: 
    build: 
      context: ./client/
      dockerfile: Dockerfile
    container_name: client_app 
    restart: always
    depends_on:
      - app
      - nginx

volumes:
  static_files:
 